#!/usr/bin/env node
/**
 * .env（gitignore済み）を読み取り、gitignore された src/env.local.ts を生成する。
 * 生成物は clasp により GAS へ push されるが、git には載らない。
 *
 * 値の優先順位: 実プロセス環境変数 > .env ファイル。
 * .env が無ければ空の ENV を生成する（fresh clone でもビルドが通る）。
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const envPath = resolve(root, ".env");
const outPath = resolve(root, "src", "env.local.ts");

// .env を許容する範囲でパース（KEY=VALUE、# はコメント、前後空白は除去）
function parseDotenv(text) {
  const out = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    // 行末コメントを除去（クォート外の ' #' のみ）
    if (!/^["']/.test(val)) {
      const hash = val.indexOf(" #");
      if (hash !== -1) val = val.slice(0, hash).trim();
    }
    // 前後のクォートを外す
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const KNOWN_KEYS = [
  "AUTH_MODE",
  "GCP_PROJECT_ID",
  "PUBSUB_TOPIC",
  "SLACK_WEBHOOK_URL",
  "HOSTS",
  "TARGET_MEETING_CODES",
  "MEETING_SLACK_MAP",
  "OAUTH_CLIENT_ID",
  "OAUTH_CLIENT_SECRET",
  "SA_CLIENT_EMAIL",
  "PUSH_SHARED_TOKEN",
  "PUBSUB_AUDIENCE",
];

const fromFile = existsSync(envPath)
  ? parseDotenv(readFileSync(envPath, "utf8"))
  : {};

const env = {};
for (const key of KNOWN_KEYS) {
  const v = process.env[key] ?? fromFile[key];
  if (v !== undefined && v !== "") env[key] = String(v);
}

const banner =
  "// AUTO-GENERATED by scripts/gen-env.mjs — DO NOT EDIT, DO NOT COMMIT.\n" +
  "// 値は .env / 環境変数に置くこと。このファイルは .gitignore 済み。\n";
const body = `var ENV: { [key: string]: string } = ${JSON.stringify(env, null, 2)};\n`;

writeFileSync(outPath, banner + body, "utf8");
console.log(
  `gen-env: wrote ${outPath} (${Object.keys(env).length} keys${
    existsSync(envPath) ? "" : ", .env not found → empty"
  })`
);
